# these are env vars + config file properties + flag options (flag > env > config)
# the application.yml file should be part of the wrapper module

# Any of the below config properties can be provided via Environment Variables prefixed  by PROXY_
# If any of the provided env variables are supposed to be "Unmarshaled" via viper, they need to have default values
# specified here so that viper may know for these env vars' existence and use them during unmarshaling

app:
  port: 8081
  logLevel: debug
  logFormat: text
  timeoutSeconds: 5
  host: http://localhost:8081
sm:
  user: admin
  password: admin
  host: http://localhost:8080
  osbApi: /v1/osb
  timeoutSeconds: 10
