apiVersion: v1
kind: Secret
metadata:
  name: {{ template "service-broker-proxy.fullname" . }}-regsecret
  labels:
    app: {{ template "service-broker-proxy.name" . }}
    chart: {{ template "service-broker-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  username: {{ .Values.app.username | b64enc }}
  password: {{ .Values.app.password | b64enc }}