apiVersion: v1
kind: Secret
metadata:
  name: {{ template "service-broker-proxy.fullname" . }}-secret
  labels:
    app: {{ template "service-broker-proxy.name" . }}
    chart: {{ template "service-broker-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  sm_user: {{ .Values.sm.user | b64enc }}
  sm_password: {{ .Values.sm.password | b64enc }}
