apiVersion: v1
kind: Secret
metadata:
  name: {{ template "service-broker-proxy.fullname" . }}
  labels:
    app: {{ template "service-broker-proxy.name" . }}
    chart: {{ template "service-broker-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  host: {{ .Values.config.serviceManager.host | b64enc }}
  user: {{ .Values.config.serviceManager.user | b64enc }}
  password: {{ .Values.config.serviceManager.password | b64enc }}