apiVersion: v1
kind: Service
metadata:
  labels:
    addon: service-broker-proxy
  name: service-broker-proxy
spec:
  type: NodePort
  ports:
    - port: 8081
  selector:
    addon: service-broker-proxy
