---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service-broker-proxy
spec:
  selector:
    matchLabels:
      app: service-broker-proxy
  template:
    metadata:
      labels:
        app: service-broker-proxy
    spec:
      containers:
      - name: service-broker-proxy
        image: ${REPOSITORY}/${PROJECT}:${VERSION}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: service-broker-proxy-image-secret
