---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service-broker-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-broker-proxy
    spec:
      containers:
      - name: service-broker-proxy
        image: ${REPOSITORY}/${PROJECT}:${VERSION}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: service-broker-proxy-image-secret
      volumes:
      - name: service-manager-secrets
        secret:
          secretName: service-manager-secret
