---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service-broker-proxy
spec:
  selector:
    matchLabels:
      app: service-broker-proxy
  template:
    metadata:
      labels:
        app: service-broker-proxy
    spec:
      containers:
      - name: service-broker-proxy
        image: ${REPOSITORY}/${PROJECT}:${VERSION}
        ports:
        - containerPort: 8080
        env:
        - name: namespace
          valueFrom:
            configMapKeyRef:
              name: service-broker-proxy-configuration
              key: namespace
        - name: service_manager_timeout
          valueFrom:
            configMapKeyRef:
              name: service-broker-proxy-configuration
              key: service_manager_timeout
        - name: service_manager_url
          valueFrom:
            configMapKeyRef:
              name: service-broker-proxy-configuration
              key: service_manager_url
        volumeMounts:
        - name: service-manager-secrets
          mountPath: "/etc/service-manager-secrets"
          readOnly: true
      volumes:
      - name: service-manager-secrets
        secret:
          secretName: service-manager-secret
