---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service-broker-proxy
spec:
  selector:
    matchLabels:
      app: service-broker-proxy
  template:
    metadata:
      labels:
        app: service-broker-proxy
    spec:
      containers:
      - name: service-broker-proxy
        image: ${REPOSITORY}/${PROJECT}:${VERSION}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: service-manager-secrets
          mountPath: "/etc/service-manager-secrets"
          readOnly: true
        - name: service-broker-proxy-configuration
          mountPath: "/etc/configuration"
          readOnly: true
      imagePullSecrets:
      - name: service-broker-proxy-image-secret
      volumes:
      - name: service-manager-secrets
        secret:
          secretName: service-manager-secret
      - name: service-broker-proxy-configuration
        configMap:
          name: service-broker-proxy-configuration
