on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event.release.tag_name }}
      CHART_NAME: service-broker-proxy-k8s-${{ github.event.release.tag_name }}
      CHART_TGZ_NAME: service-broker-proxy-k8s-${{ github.event.release.tag_name }}.tgz
      CHART_URL: https://github.com/Peripli/service-broker-proxy-k8s/releases/download/${{ github.event.release.tag_name }}/service-broker-proxy-k8s-${{ github.event.release.tag_name }}.tgz
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        run: |
          sed -i -e 's/tag: master/tag: '${TAG_NAME:-master}'/g' ./charts/service-broker-proxy-k8s/values.yaml | sh
          mkdir out
          helm package --app-version ${TAG_NAME:-"master"} --version ${TAG_NAME:-"0.0.0"} -d ./out charts/service-broker-proxy-k8s
          helm repo index ./out
          sed -i "s|${CHART_TGZ_NAME}|${CHART_URL}|g" ./out/index.yaml | sh
          mv ./out/index.yaml ./out/${CHART_NAME}.yaml

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
          file_glob: true
